http:
  port: 3000

service-endpoints:
  payment-service:
    path: '/api/payment/'
    protocol: 'http'
    host: 'localhost'
    port: 9005
    changeOrigin: true  

  order-service:
    path: '/api/order/'
    protocol: 'https'
    host: 'order.foo.com'
    changeOrigin: true        
  
  support-service:
    path: '/api/support/'
    protocol: 'https'
    host: 'localhost',
    port: 9007
    changeOrigin: true        

  default-service:
    path: '/api/'
    protocol: 'https'
    host: 'order.boo.com'
    changeOrigin: true        

policies:
  - proxy
